name: CI
on:
  - pull_request
jobs:

  job1:
    runs-on: ubuntu-latest
    name: Build Catalog Service
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and test
        working-directory: catalog-service
        run: |
          export SHELL=/bin/bash
          ./gradlew build
      - name: Build Docker image for Catalog Service
        working-directory: catalog-service
        run: |
          export SHELL=/bin/bash
          docker build -t catalogservice .
      - name: Run Docker container for Catalog Service
        working-directory: catalog-service
        run: |
          docker run -d -p 8080:8080 catalogservice

  job2:
    runs-on: ubuntu-latest
    name: Build Client Micro-Service
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and test
        working-directory: client-service
        run: |
          export SHELL=/bin/bash
          ./gradlew build
      - name: Build Docker image for Client Micro-Service
        working-directory: client-service
        run: |
          export SHELL=/bin/bash
          docker build -t clientservice .
      - name: Run Docker container for Client Micro-Service
        working-directory: client-service
        run: |
          docker run -d -p 8081:8081 clientservice

  job3:
    runs-on: ubuntu-latest
    name: Build Front-End
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: front-end
        run: |
          npm install
      - name: Build the Front-End
        working-directory: front-end
        run: |
          npm run build
      - name: Build Docker image for Front-End
        working-directory: front-end
        run: |
          docker build -t frontend .
      - name: Run Docker container for Front-End
        working-directory: front-end
        run: |
          docker run -d -p 3000:3000 frontend
